### ISSUE TITLE
A question in function simple_context

### ISSUE THREAD

**Issue by wai7niu8** [udibr/headlines#9]
Hi:
in train.ipynb, i'm confused about this line:
activation_energies = activation_energies + -1e20*K.expand_dims(1.-K.cast(mask[:, :maxlend],'float32'),1)
i think this line is unnecessary(i maybe wrong), please explain this line for me in detail.
And, when computing the attention weights, i think we should only use the current word's ht(ht is the time step t's hidden state) in decoding, but in the function simple_context, it use all headline words' ht every time step?
What's more,can you show me the paper or other references about how to implement the attention layer, i think i am not particularly familiar with it. Thank you.

**Comment by udibr** [comment]
the first line in the README file gives a link to the paper on which the code is based.
please read it several times from start to finish until you feel you understand it.
Also read the references it gives.

the line you asked about reduce the energy  by a huge value in all places in which mask is zero in the part of the input (0:maxlend) which came from the article.
Latter I take a softmax of the energy and as a result locations in which the mask was zero will have almost zero weight.

simple_context works at once on all the time steps.

**Comment by xtr33me** [comment]
Hey Udibr
Thought I would ask here since you often seem to have the answer for all my issues :)  So currently I have gotten a pc up and running with some GPU lovin so my training is now going so much better.  So after going through some iterations I thought I would start workin with "predict" and see if I would be able to run it without issue against some trained data. I ran into a few issues. One I have listed below and I was able to get around, but the one I have not had luck with resolving yet is the error: 
AttributeError: 'Tensor' object has no attribute 'ndim'

As you can see in the dump below, I get it when it is accessing ndim on mask. A few things here...I am using Tensorflow and from what I have seen, this may be an issue in Keras. I am continuing to look into this and will psot something should I figure out what is going on. However, should you have any solutions, throw them my way.  Thanks!



>failed to find layer timedistributed_1 in model 
stopping to load all other layers
Traceback (most recent call last):
  File "predict.py", line 331, in <module>
    model.add(SimpleContext(name='simplecontext_1'))
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.8-py2.7.egg/keras/models.py", line 308, in add
    output_tensor = layer(self.outputs[0])
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.8-py2.7.egg/keras/engine/topology.py", line 515, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.8-py2.7.egg/keras/engine/topology.py", line 573, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.8-py2.7.egg/keras/engine/topology.py", line 150, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.8-py2.7.egg/keras/layers/core.py", line 554, in call
    return self.function(x, **arguments)
  File "predict.py", line 298, in simple_context
    assert mask.ndim == 2
AttributeError: 'Tensor' object has no attribute 'ndim'


One other thing that I was just curious as to why it was an issue, if you know. When I initially ran predict, it failed with the below message. I was able to resolve it by changing both maxlend and maxlenh to the same value of 25. Just curious if this is an issue or not and if you have any insight as to why it is an issue in Tensorflow. 
ValueError: Dimensions 25 and 50 are not compatible

> File "predict.py", line 296, in simple_context
    activation_energies = K.batch_dot(head_activations, desc_activations, axes=([2],[2]))
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.8-py2.7.egg/keras/backend/tensorflow_backend.py", line 367, in batch_dot
    out = tf.batch_matmul(x, y, adj_x=adj_x, adj_y=adj_y)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 390, in _batch_mat_mul
    adj_y=adj_y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1725, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 1609, in _BatchMatMulShape
    inner_a.assert_is_compatible_with(inner_b)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_shape.py", line 108, in assert_is_compatible_with
    % (self, other))
ValueError: Dimensions 25 and 50 are not compatible
